# BugReports Configuration
# Подробная документация: https://vk.com/defaltmark

# Настройки базы данных
# Тип базы данных (поддерживается только sqlite на данный момент)
# Файл базы данных будет создан в папке плагина
database:
  type: sqlite
  file: database.db

# Категории репортов
# ВАЖНО: Хотя плагин поддерживает неограниченное количество категорий,
# рекомендуется не создавать более 15-20 категорий для каждого типа.
# Большое количество категорий может усложнить навигацию для пользователей.
# 
# Каждая категория будет отображаться в отдельном слоте в GUI.
# При большом количестве категорий они будут разделены на страницы.
categories:
  # Категории для баг-репортов
  bugs:
    - "Игровой процесс"  # Баги, связанные с игровой механикой
    - "Интерфейс"        # Проблемы с GUI, инвентарем и т.д.
    - "Производительность" # Лаги, проблемы с производительностью
    - "Другое"           # Прочие баги
  # Категории для предложений
  suggestions:
    - "Игровой процесс"  # Предложения по улучшению геймплея
    - "Экономика"        # Идеи по экономике сервера
    - "Команды"          # Предложения новых команд
    - "Другое"           # Прочие предложения

# Статусы репортов
# Вы можете изменить или добавить свои статусы
# Первый статус в списке будет использоваться как статус по умолчанию
statuses:
  - "Новый"           # Только что созданный репорт
  - "В обработке"     # Репорт рассматривается администрацией
  - "Исправлено"      # Баг исправлен или предложение реализовано
  - "Отклонено"       # Репорт отклонен
  - "Завершено"       # Работа над репортом завершена

# Ограничения для репортов
limits:
  min-description-length: 10    # Минимальная длина описания
  max-description-length: 500   # Максимальная длина описания
  cooldown-minutes: 5          # Задержка между созданием репортов
  max-active-reports: 3        # Максимальное количество активных репортов у игрока

# Права доступа
permissions:
  create-report: "bugreports.create"  # Право на создание репортов
  admin: "bugreports.admin"           # Право на администрирование репортов

# Настройки уведомлений
notifications:
  # Звук при получении уведомления
  # Список доступных звуков: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
  sound: ENTITY_EXPERIENCE_ORB_PICKUP
  # Отправлять уведомление при входе игрока
  notify-on-join: true
  # Автоматически открывать GUI со статусом репортов при входе
  auto-open-status: false
  # Интервал проверки новых статусов (в секундах)
  check-interval: 300

# Настройки админ-панели
admin:
  # Уведомлять админов о новых репортах
  notify-new-reports: true
  # Показывать количество новых репортов в табе
  show-count-in-tab: true
  # Автоматически обновлять админ GUI (в секундах, 0 - отключено)
  auto-refresh: 30

# Настройки проверки обновлений
updates:
  # Включить/выключить проверку обновлений
  enabled: true
  # Уведомлять администраторов при входе о наличии обновлений
  notify-admins: true
  # Показывать сообщение о текущей версии при запуске
  show-version-info: true
  # Интервал проверки обновлений (в часах)
  check-interval: 24 