name: BugReports
version: '1.1.0'
main: com.beastmark.bugreports.BugReports
api-version: '1.19'
depend: [PlaceholderAPI]
softdepend: []
authors: [BeastMark]
description: Плагин для управления баг-репортами и предложениями с поддержкой Telegram
website: https://vk.com/defaltmark

commands:
  bugreport:
    description: Создать баг-репорт
    usage: /bugreport
    aliases: [br]
  suggestion:
    description: Создать предложение
    usage: /suggestion
    aliases: [sug]
  reportadmin:
    description: Команды администратора
    usage: /reportadmin
    aliases: [ra]
  reportstats:
    description: Статистика репортов
    usage: /reportstats
    aliases: [rs]
  telegram:
    description: Управление Telegram интеграцией
    usage: /telegram
    aliases: [tg]

permissions:
  bugreports.create:
    description: Разрешает создавать репорты
    default: true
  bugreports.admin:
    description: Доступ к админ-командам
    default: op
  bugreports.telegram:
    description: Доступ к Telegram интеграции
    default: op 